global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth_service:5001']
    metrics_path: '/metrics'

  - job_name: 'user-service'
    static_configs:
      - targets: ['user_service:5002']
    metrics_path: '/metrics'

  - job_name: 'book-service'
    static_configs:
      - targets: ['book_service:8080']
    metrics_path: '/metrics'
